samples: config/samples.tsv

units: config/units.tsv

pipeline: 
  SEQ: mouse
  TYPE: WES
  PAIRED: True

tools: 
  fastqc: True
  bqsr: True
  facets: True
  cnv_facets: True
  flagstat: True
  mosdepth: True
  annovar: True
  hsmetrics: True
  haplotype: True 
  mutect2:
    samples: True
    annovar: True
    oncotator: True
    oncotator_exom: True
  mutect2_pon:
    samples: False
    oncotator: False
    oncotator_exom: False
  mutect2_tumor_only: 
    samples: False
    annovar: False
    oncotator: False
    oncotator_exom: False
  mutect2_tumor_only_pon: 
    samples: False
    oncotator: False
    oncotator_exom: False


